### ISSUE TITLE
How do i resume training of a style_adapter checkpoint?

### ISSUE THREAD

**Issue by surfingnirvana** [Baojch/StyleDrop-PyTorch-windows#1]
How do i resume training of a style_adapter checkpoint? Is it possible to train on 512 by 512 pixel images?  The original code has some kind of  upscaling integrated right?

**Comment by Baojch** [comment]
I apologize for not attempting to utilize the resume training feature available in the [StyleDrop-PyTorch for Windows repository](https://github.com/endman100/StyleDrop-PyTorch-windows/tree/main). Although the training code includes the option for resuming training, I regret that I haven't explored its functionality yet. 

![4020481858](https://github.com/Baojch/StyleDrop-PyTorch-windows/assets/89232027/b57d3200-850e-452d-b564-531662a6da1d)

Training on 512 by 512 pixel images appears feasible, given my practice of including pictures at different scales throughout the training process.
